In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", 50)

In [2]:
pan = pd.read_csv('../to_csv/pan.csv').drop('Unnamed: 0', axis=1)
pan.head()

,Set,Categorie Montage,Dossier Patient,Patient,Session,File N°,interval_index,interval_start_time,mean_nni,sdnn,sdsd,nni_50,pnni_50,nni_20,pnni_20,rmssd,median_nni,range_nni,cvsd,cvnni,mean_hr,max_hr,min_hr,std_hr,lf,hf,vlf,lf_hf_ratio,csi,cvi,Modified_csi,sampen,sd1,sd2,ratio_sd2_sd1,label
0,train,01_tcp_ar,86,8643,s001_2012_02_22,t000,0.0,0.0,NaN,NaN,NaN,1.0,3.571429,4.0,14.285714,NaN,NaN,218.750000,NaN,NaN,NaN,178.604651,108.169014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1,train,01_tcp_ar,86,8643,s001_2012_02_22,t000,1.0,10000.0,NaN,NaN,NaN,7.0,25.925926,11.0,40.740741,NaN,NaN,343.750000,NaN,NaN,NaN,182.857143,89.302326,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
2,train,01_tcp_ar,86,8643,s001_2012_02_22,t000,2.0,20000.0,NaN,NaN,NaN,3.0,10.714286,6.0,21.428571,NaN,NaN,351.562500,NaN,NaN,NaN,178.604651,87.272727,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
3,train,01_tcp_ar,86,8643,s001_2012_02_22,t000,3.0,30000.0,NaN,NaN,NaN,5.0,17.857143,8.0,28.571429,NaN,NaN,282.226562,NaN,NaN,NaN,180.705882,97.678855,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
4,train,01_tcp_ar,86,8643,s001_2012_02_22,t000,4.0,40000.0,NaN,NaN,NaN,6.0,26.086957,9.0,39.130435,NaN,NaN,563.151042,NaN,NaN,NaN,134.148472,59.381443,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0

In [3]:
pan['Date'] = pan.Session.str[-10:]
pan['Date'] = pan.Date.str.replace('_', '/')
pan['Date'] =  pd.to_datetime(pan['Date'], format='%Y/%m/%d').dt.strftime('%d/%m/%Y')

pan.Session = pan.Session.str[:4]

cols = pan.columns.tolist()
cols = cols[:5] + ['Date'] + cols[5:-1]

pan = pan[cols]

pan.head()

,Set,Categorie Montage,Dossier Patient,Patient,Session,Date,File N°,interval_index,interval_start_time,mean_nni,sdnn,sdsd,nni_50,pnni_50,nni_20,pnni_20,rmssd,median_nni,range_nni,cvsd,cvnni,mean_hr,max_hr,min_hr,std_hr,lf,hf,vlf,lf_hf_ratio,csi,cvi,Modified_csi,sampen,sd1,sd2,ratio_sd2_sd1,label
0,train,01_tcp_ar,86,8643,s001,22/02/2012,t000,0.0,0.0,NaN,NaN,NaN,1.0,3.571429,4.0,14.285714,NaN,NaN,218.750000,NaN,NaN,NaN,178.604651,108.169014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1,train,01_tcp_ar,86,8643,s001,22/02/2012,t000,1.0,10000.0,NaN,NaN,NaN,7.0,25.925926,11.0,40.740741,NaN,NaN,343.750000,NaN,NaN,NaN,182.857143,89.302326,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
2,train,01_tcp_ar,86,8643,s001,22/02/2012,t000,2.0,20000.0,NaN,NaN,NaN,3.0,10.714286,6.0,21.428571,NaN,NaN,351.562500,NaN,NaN,NaN,178.604651,87.272727,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
3,train,01_tcp_ar,86,8643,s001,22/02/2012,t000,3.0,30000.0,NaN,NaN,NaN,5.0,17.857143,8.0,28.571429,NaN,NaN,282.226562,NaN,NaN,NaN,180.705882,97.678855,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
4,train,01_tcp_ar,86,8643,s001,22/02/2012,t000,4.0,40000.0,NaN,NaN,NaN,6.0,26.086957,9.0,39.130435,NaN,NaN,563.151042,NaN,NaN,NaN,134.148472,59.381443,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0

In [4]:
pan.describe(include='all')

,Set,Categorie Montage,Dossier Patient,Patient,Session,Date,File N°,interval_index,interval_start_time,mean_nni,sdnn,sdsd,nni_50,pnni_50,nni_20,pnni_20,rmssd,median_nni,range_nni,cvsd,cvnni,mean_hr,max_hr,min_hr,std_hr,lf,hf,vlf,lf_hf_ratio,csi,cvi,Modified_csi,sampen,sd1,sd2,ratio_sd2_sd1,label
count,265081,265081,265081.000000,265081.000000,265081,265081,265081,265081.000000,2.650810e+05,198432.000000,197110.000000,197110.000000,259366.000000,259366.000000,259366.000000,259366.000000,197110.000000,198432.000000,249422.000000,196516.000000,196516.000000,1.984320e+05,2.494220e+05,2.494220e+05,196516.000000,125000.000000,125000.000000,125000.000000,124572.000000,160023.000000,1.605220e+05,160023.000000,2.301060e+05,160522.000000,160522.000000,160023.000000,261647.000000
unique,2,3,NaN,NaN,39,730,33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,train,01_tcp_ar,NaN,NaN,s002,23/09/2014,t000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,214925,212817,NaN,NaN,40116,2832,52883,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,84.351187,8487.042297,NaN,NaN,NaN,42.815173,4.281517e+05,725.334849,21.625615,13.561086,0.950695,5.348270,1.904988,10.971614,14.169632,727.204664,104.420419,0.019464,0.030303,inf,inf,inf,2.793807,532.683258,113.979210,345.738009,10.694034,4.966113,-inf,812.656826,inf,9.272719,38.582435,4.966113,0.067000
std,NaN,NaN,30.499020,3052.147952,NaN,NaN,NaN,43.188979,4.318898e+05,183.773333,33.815207,20.385226,1.706936,9.525488,2.587004,14.287999,21.177344,185.791261,155.807590,0.029997,0.049674,NaN,NaN,NaN,5.477289,1784.194775,400.901521,1154.570862,13.183215,2.892555,NaN,1135.158493,NaN,11.047271,42.328071,2.892555,0.244654
min,NaN,NaN,0.000000,2.000000,NaN,NaN,NaN,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.398230e+01,3.398230e+01,3.339130e+01,0.000000,0.000000,0.000000,0.000000,0.019079,0.247265,-inf,0.272844,-0.000000e+00,0.000000,0.000000,0.247265,0.000000
25%,NaN,NaN,70.000000,7032.000000,NaN,NaN,NaN,14.000000,1.400000e+05,613.769531,3.812110,2.500000,0.000000,0.000000,0.000000,0.000000,2.618615,616.000000,15.625000,0.004058,0.005715,7.283478e+01,7.876923e+01,7.075472e+01,0.489060,21.455194,2.008112,19.348502,3.181243,3.062211,2.602641e+00,190.111576,4.340969e-01,2.097413,11.397043,3.062211,0.000000
50%,NaN,NaN,91.000000,9104.000000,NaN,NaN,NaN,30.000000,3.000000e+05,709.428571,9.847319,5.823094,0.000000,0.000000,1.000000,5.128205,6.176324,710.937500,42.968750,0.008309,0.013239,8.479274e+01,9.365854e+01,8.347826e+01,1.042062,112.332034,14.932354,83.917828,6.919878,4.225416,3.359209e+00,454.275844,7.457909e-01,5.516155,25.575132,4.225416,0.000000
75%,NaN,NaN,104.000000,10427.000000,NaN,NaN,NaN,55.000000,5.500000e+05,825.666667,24.901038,16.603462,1.000000,8.333333,3.000000,18.750000,17.421991,828.125000,120.000000,0.022130,0.032162,9.820003e+01,1.228800e+02,9.846154e+01,2.479544,427.747556,76.729338,298.398552,13.708108,6.001940,3.966115e+00,986.163019,inf,12.226333,49.894162,6.001940,0.000000
max,NaN,NaN,134.000000,13407.000000,NaN,NaN,NaN,359.000000,3.590000e+06,1765.625000,620.546616,517.578125,14.000000,87.500000,16.000000,88.888889,517.578125,1781.250000,1488.281250,0.755179,0.884310,inf,inf,inf,72.368898,85139.275840,20969.416732,74679.131280,800.529887,52.867535,6.251395e+00,32305.208100,inf,304.591498,748.133738,52.867535,1.000000

In [5]:
pan['Dossier Patient'] = pan['Dossier Patient'].astype(str)
pan['Patient'] = pan['Patient'].astype(str)

In [6]:
pan.describe(include='all')

,Set,Categorie Montage,Dossier Patient,Patient,Session,Date,File N°,interval_index,interval_start_time,mean_nni,sdnn,sdsd,nni_50,pnni_50,nni_20,pnni_20,rmssd,median_nni,range_nni,cvsd,cvnni,mean_hr,max_hr,min_hr,std_hr,lf,hf,vlf,lf_hf_ratio,csi,cvi,Modified_csi,sampen,sd1,sd2,ratio_sd2_sd1,label
count,265081,265081,265081,265081,265081,265081,265081,265081.000000,2.650810e+05,198432.000000,197110.000000,197110.000000,259366.000000,259366.000000,259366.000000,259366.000000,197110.000000,198432.000000,249422.000000,196516.000000,196516.000000,1.984320e+05,2.494220e+05,2.494220e+05,196516.000000,125000.000000,125000.000000,125000.000000,124572.000000,160023.000000,1.605220e+05,160023.000000,2.301060e+05,160522.000000,160522.000000,160023.000000,261647.000000
unique,2,3,121,458,39,730,33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,train,01_tcp_ar,104,9578,s002,23/09/2014,t000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,214925,212817,13562,11164,40116,2832,52883,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42.815173,4.281517e+05,725.334849,21.625615,13.561086,0.950695,5.348270,1.904988,10.971614,14.169632,727.204664,104.420419,0.019464,0.030303,inf,inf,inf,2.793807,532.683258,113.979210,345.738009,10.694034,4.966113,-inf,812.656826,inf,9.272719,38.582435,4.966113,0.067000
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,43.188979,4.318898e+05,183.773333,33.815207,20.385226,1.706936,9.525488,2.587004,14.287999,21.177344,185.791261,155.807590,0.029997,0.049674,NaN,NaN,NaN,5.477289,1784.194775,400.901521,1154.570862,13.183215,2.892555,NaN,1135.158493,NaN,11.047271,42.328071,2.892555,0.244654
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.398230e+01,3.398230e+01,3.339130e+01,0.000000,0.000000,0.000000,0.000000,0.019079,0.247265,-inf,0.272844,-0.000000e+00,0.000000,0.000000,0.247265,0.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.000000,1.400000e+05,613.769531,3.812110,2.500000,0.000000,0.000000,0.000000,0.000000,2.618615,616.000000,15.625000,0.004058,0.005715,7.283478e+01,7.876923e+01,7.075472e+01,0.489060,21.455194,2.008112,19.348502,3.181243,3.062211,2.602641e+00,190.111576,4.340969e-01,2.097413,11.397043,3.062211,0.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.000000,3.000000e+05,709.428571,9.847319,5.823094,0.000000,0.000000,1.000000,5.128205,6.176324,710.937500,42.968750,0.008309,0.013239,8.479274e+01,9.365854e+01,8.347826e+01,1.042062,112.332034,14.932354,83.917828,6.919878,4.225416,3.359209e+00,454.275844,7.457909e-01,5.516155,25.575132,4.225416,0.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,55.000000,5.500000e+05,825.666667,24.901038,16.603462,1.000000,8.333333,3.000000,18.750000,17.421991,828.125000,120.000000,0.022130,0.032162,9.820003e+01,1.228800e+02,9.846154e+01,2.479544,427.747556,76.729338,298.398552,13.708108,6.001940,3.966115e+00,986.163019,inf,12.226333,49.894162,6.001940,0.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,359.000000,3.590000e+06,1765.625000,620.546616,517.578125,14.000000,87.500000,16.000000,88.888889,517.578125,1781.250000,1488.281250,0.755179,0.884310,inf,inf,inf,72.368898,85139.275840,20969.416732,74679.131280,800.529887,52.867535,6.251395e+00,32305.208100,inf,304.591498,748.133738,52.867535,1.000000

In [7]:
percentage = pan[['Patient', 'label']].groupby(['Patient']).agg(['sum', 'count'])

In [8]:
percentage.columns

MultiIndex([('label',   'sum'),
            ('label', 'count')],
           )

In [9]:
percentage[('label', 'percent')] = (percentage[('label',   'sum')] / percentage[('label',   'count')]) * 100

In [10]:
percentage

             label
               sum count    percent
Patient
10020    111.74689   351  31.836721
10022     55.13887  2555   2.158077
10023      0.00000   373   0.000000
10035      0.00000   132   0.000000
1006      17.65080   493   3.580284
...            ...   ...        ...
9902       0.00000   155   0.000000
9906       0.00000   282   0.000000
9932       9.93164  1309   0.758720
9934      14.51991   683   2.125902
9994      10.59720  1540   0.688130

[458 rows x 3 columns]