In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", 50)

In [2]:
swt = pd.read_csv('../to_csv/swt.csv').drop('Unnamed: 0', axis=1)
swt.head()

,Set,Categorie Montage,Dossier Patient,Patient,Session,File N°,interval_index,interval_start_time,mean_nni,sdnn,sdsd,nni_50,pnni_50,nni_20,pnni_20,rmssd,median_nni,range_nni,cvsd,cvnni,mean_hr,max_hr,min_hr,std_hr,lf,hf,vlf,lf_hf_ratio,csi,cvi,Modified_csi,sampen,sd1,sd2,ratio_sd2_sd1,label
0,train,01_tcp_ar,86,8643,s001_2012_02_22,t000,0.0,0.0,NaN,NaN,NaN,0.0,0.000000,3.0,17.647059,NaN,NaN,66.406250,NaN,NaN,NaN,120.000000,105.931034,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1,train,01_tcp_ar,86,8643,s001_2012_02_22,t000,1.0,10000.0,NaN,NaN,NaN,4.0,22.222222,6.0,33.333333,NaN,NaN,175.781250,NaN,NaN,NaN,123.870968,90.887574,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
2,train,01_tcp_ar,86,8643,s001_2012_02_22,t000,2.0,20000.0,600.043403,48.993541,33.789686,2.0,11.111111,4.0,22.222222,34.957824,599.609375,152.343750,0.058259,0.081650,100.606071,112.941176,87.771429,7.749811,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
3,train,01_tcp_ar,86,8643,s001_2012_02_22,t000,3.0,30000.0,636.827257,25.195199,18.188169,0.0,0.000000,5.0,27.777778,18.431833,634.765625,89.843750,0.028943,0.039564,94.356598,102.400000,88.786127,3.632898,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
4,train,01_tcp_ar,86,8643,s001_2012_02_22,t000,4.0,40000.0,552.191840,57.491179,26.590452,2.0,11.111111,6.0,33.333333,28.287609,558.593750,189.453125,0.051228,0.104115,109.903330,140.917431,97.523810,12.377808,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0

In [3]:
swt['Date'] = swt.Session.str[-10:]
swt['Date'] = swt.Date.str.replace('_', '/')
swt['Date'] =  pd.to_datetime(swt['Date'], format='%Y/%m/%d').dt.strftime('%d/%m/%Y')

swt.Session = swt.Session.str[:4]

cols = swt.columns.tolist()
cols = cols[:5] + ['Date'] + cols[5:-1]

swt = swt[cols]

swt.head()

,Set,Categorie Montage,Dossier Patient,Patient,Session,Date,File N°,interval_index,interval_start_time,mean_nni,sdnn,sdsd,nni_50,pnni_50,nni_20,pnni_20,rmssd,median_nni,range_nni,cvsd,cvnni,mean_hr,max_hr,min_hr,std_hr,lf,hf,vlf,lf_hf_ratio,csi,cvi,Modified_csi,sampen,sd1,sd2,ratio_sd2_sd1,label
0,train,01_tcp_ar,86,8643,s001,22/02/2012,t000,0.0,0.0,NaN,NaN,NaN,0.0,0.000000,3.0,17.647059,NaN,NaN,66.406250,NaN,NaN,NaN,120.000000,105.931034,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1,train,01_tcp_ar,86,8643,s001,22/02/2012,t000,1.0,10000.0,NaN,NaN,NaN,4.0,22.222222,6.0,33.333333,NaN,NaN,175.781250,NaN,NaN,NaN,123.870968,90.887574,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
2,train,01_tcp_ar,86,8643,s001,22/02/2012,t000,2.0,20000.0,600.043403,48.993541,33.789686,2.0,11.111111,4.0,22.222222,34.957824,599.609375,152.343750,0.058259,0.081650,100.606071,112.941176,87.771429,7.749811,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
3,train,01_tcp_ar,86,8643,s001,22/02/2012,t000,3.0,30000.0,636.827257,25.195199,18.188169,0.0,0.000000,5.0,27.777778,18.431833,634.765625,89.843750,0.028943,0.039564,94.356598,102.400000,88.786127,3.632898,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
4,train,01_tcp_ar,86,8643,s001,22/02/2012,t000,4.0,40000.0,552.191840,57.491179,26.590452,2.0,11.111111,6.0,33.333333,28.287609,558.593750,189.453125,0.051228,0.104115,109.903330,140.917431,97.523810,12.377808,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0

In [4]:
swt.describe(include='all')

,Set,Categorie Montage,Dossier Patient,Patient,Session,Date,File N°,interval_index,interval_start_time,mean_nni,sdnn,sdsd,nni_50,pnni_50,nni_20,pnni_20,rmssd,median_nni,range_nni,cvsd,cvnni,mean_hr,max_hr,min_hr,std_hr,lf,hf,vlf,lf_hf_ratio,csi,cvi,Modified_csi,sampen,sd1,sd2,ratio_sd2_sd1,label
count,305522,305522,305522.000000,305522.000000,305522,305522,305522,305522.000000,3.055220e+05,270426.000000,265907.000000,265907.000000,287299.000000,287299.000000,287299.000000,287299.000000,265907.000000,270426.000000,286540.000000,263908.000000,263908.000000,2.704260e+05,2.865400e+05,2.865400e+05,263908.000000,194665.000000,194665.000000,194665.000000,193199.000000,233422.000000,2.344600e+05,233422.000000,2.570050e+05,234460.000000,234460.000000,233422.000000,301475.000000
unique,2,3,NaN,NaN,39,915,33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,train,01_tcp_ar,NaN,NaN,s001,04/05/2014,t000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,248620,230259,NaN,NaN,58356,3374,83514,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,80.812995,8132.601659,NaN,NaN,NaN,46.163694,4.616369e+05,712.837635,21.959168,13.617920,0.546298,3.998514,1.173081,8.798413,14.301235,714.247475,71.499842,0.020071,0.031360,inf,inf,inf,2.985544,983.672409,277.359936,576.028481,10.498457,5.035201,-inf,944.409855,inf,11.177081,45.789432,5.035201,0.067120
std,NaN,NaN,33.233852,3325.505494,NaN,NaN,NaN,45.429059,4.542906e+05,203.343434,38.431423,23.510660,1.287999,9.348878,1.992219,14.319919,24.809010,205.705495,118.640867,0.035258,0.056031,NaN,NaN,NaN,6.244466,3364.816816,1081.059245,2196.541268,12.253101,2.971028,NaN,1387.794808,NaN,15.818004,57.629238,2.971028,0.244746
min,NaN,NaN,0.000000,2.000000,NaN,NaN,NaN,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.339130e+01,3.337969e+01,3.337969e+01,0.000000,0.000000,0.000000,0.000000,0.035663,0.239951,-inf,0.724422,-0.000000e+00,0.000000,0.000000,0.239951,0.000000
25%,NaN,NaN,65.000000,6514.000000,NaN,NaN,NaN,15.000000,1.500000e+05,605.841064,3.636521,2.461538,0.000000,0.000000,0.000000,0.000000,2.557241,605.468750,11.718750,0.004012,0.005540,7.299018e+01,7.614213e+01,7.013699e+01,0.473834,20.225551,1.908666,19.518818,3.003923,3.104448,2.572943e+00,191.007660,3.761194e-01,2.047734,10.986874,3.104448,0.000000
50%,NaN,NaN,88.000000,8835.000000,NaN,NaN,NaN,33.000000,3.300000e+05,707.714286,8.712215,5.208333,0.000000,0.000000,0.000000,0.000000,5.524272,710.000000,27.343750,0.007649,0.012031,8.506417e+01,8.928571e+01,8.196721e+01,0.957705,126.498608,14.662858,95.624890,6.639001,4.277588,3.337644e+00,487.748821,5.950554e-01,5.210226,25.818917,4.277588,0.000000
75%,NaN,NaN,104.000000,10418.000000,NaN,NaN,NaN,59.000000,5.900000e+05,824.218750,22.048342,13.662877,0.000000,0.000000,2.000000,14.285714,14.422205,828.000000,72.000000,0.018080,0.028279,9.953165e+01,1.079137e+02,9.540373e+01,2.170809,578.524093,107.555038,408.780536,13.640625,6.069021,4.056171e+00,1138.703478,8.821133e-01,13.484533,56.153517,6.069021,0.000000
max,NaN,NaN,134.000000,13407.000000,NaN,NaN,NaN,359.000000,3.590000e+06,1796.875000,679.660936,691.406250,19.000000,88.888889,21.000000,90.909091,691.406250,1796.875000,1440.000000,0.772812,0.835118,inf,inf,inf,75.611711,175342.049783,115607.049601,170274.136408,332.921919,52.958695,6.672461e+00,39576.034623,inf,529.447002,883.858934,52.958695,1.000000

In [5]:
swt['Dossier Patient'] = swt['Dossier Patient'].astype(str)
swt['Patient'] = swt['Patient'].astype(str)

In [6]:
swt.describe(include='all')

,Set,Categorie Montage,Dossier Patient,Patient,Session,Date,File N°,interval_index,interval_start_time,mean_nni,sdnn,sdsd,nni_50,pnni_50,nni_20,pnni_20,rmssd,median_nni,range_nni,cvsd,cvnni,mean_hr,max_hr,min_hr,std_hr,lf,hf,vlf,lf_hf_ratio,csi,cvi,Modified_csi,sampen,sd1,sd2,ratio_sd2_sd1,label
count,305522,305522,305522,305522,305522,305522,305522,305522.000000,3.055220e+05,270426.000000,265907.000000,265907.000000,287299.000000,287299.000000,287299.000000,287299.000000,265907.000000,270426.000000,286540.000000,263908.000000,263908.000000,2.704260e+05,2.865400e+05,2.865400e+05,263908.000000,194665.000000,194665.000000,194665.000000,193199.000000,233422.000000,2.344600e+05,233422.000000,2.570050e+05,234460.000000,234460.000000,233422.000000,301475.000000
unique,2,3,132,604,39,915,33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,train,01_tcp_ar,104,9578,s001,04/05/2014,t000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,248620,230259,13930,11634,58356,3374,83514,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.163694,4.616369e+05,712.837635,21.959168,13.617920,0.546298,3.998514,1.173081,8.798413,14.301235,714.247475,71.499842,0.020071,0.031360,inf,inf,inf,2.985544,983.672409,277.359936,576.028481,10.498457,5.035201,-inf,944.409855,inf,11.177081,45.789432,5.035201,0.067120
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.429059,4.542906e+05,203.343434,38.431423,23.510660,1.287999,9.348878,1.992219,14.319919,24.809010,205.705495,118.640867,0.035258,0.056031,NaN,NaN,NaN,6.244466,3364.816816,1081.059245,2196.541268,12.253101,2.971028,NaN,1387.794808,NaN,15.818004,57.629238,2.971028,0.244746
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.339130e+01,3.337969e+01,3.337969e+01,0.000000,0.000000,0.000000,0.000000,0.035663,0.239951,-inf,0.724422,-0.000000e+00,0.000000,0.000000,0.239951,0.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.000000,1.500000e+05,605.841064,3.636521,2.461538,0.000000,0.000000,0.000000,0.000000,2.557241,605.468750,11.718750,0.004012,0.005540,7.299018e+01,7.614213e+01,7.013699e+01,0.473834,20.225551,1.908666,19.518818,3.003923,3.104448,2.572943e+00,191.007660,3.761194e-01,2.047734,10.986874,3.104448,0.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.000000,3.300000e+05,707.714286,8.712215,5.208333,0.000000,0.000000,0.000000,0.000000,5.524272,710.000000,27.343750,0.007649,0.012031,8.506417e+01,8.928571e+01,8.196721e+01,0.957705,126.498608,14.662858,95.624890,6.639001,4.277588,3.337644e+00,487.748821,5.950554e-01,5.210226,25.818917,4.277588,0.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,59.000000,5.900000e+05,824.218750,22.048342,13.662877,0.000000,0.000000,2.000000,14.285714,14.422205,828.000000,72.000000,0.018080,0.028279,9.953165e+01,1.079137e+02,9.540373e+01,2.170809,578.524093,107.555038,408.780536,13.640625,6.069021,4.056171e+00,1138.703478,8.821133e-01,13.484533,56.153517,6.069021,0.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,359.000000,3.590000e+06,1796.875000,679.660936,691.406250,19.000000,88.888889,21.000000,90.909091,691.406250,1796.875000,1440.000000,0.772812,0.835118,inf,inf,inf,75.611711,175342.049783,115607.049601,170274.136408,332.921919,52.958695,6.672461e+00,39576.034623,inf,529.447002,883.858934,52.958695,1.000000

In [8]:
percentage = swt[['Patient', 'label']].groupby(['Patient']).agg(['sum', 'count'])

In [9]:
percentage.columns

MultiIndex([('label',   'sum'),
            ('label', 'count')],
           )

In [10]:
percentage[('label', 'percent')] = (percentage[('label',   'sum')] / percentage[('label',   'count')]) * 100

In [11]:
percentage

             label
               sum count    percent
Patient
10020    111.74689   351  31.836721
10022     55.13887  2746   2.007971
10023      0.00000   373   0.000000
10035      0.00000   132   0.000000
1006      17.65080   495   3.565818
...            ...   ...        ...
9906       0.00000   282   0.000000
9932       9.93164  1309   0.758720
9934      14.51991   683   2.125902
9958       0.00000   258   0.000000
9994      10.59720  1540   0.688130

[604 rows x 3 columns]